import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "10mb" }));

// Lazy Google GenAI Client
let genAIClient: GoogleGenAI | null = null;
function getGenAI(): GoogleGenAI {
  if (!genAIClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    genAIClient = new GoogleGenAI({
      apiKey: apiKey || "",
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return genAIClient;
}

// API Routes
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", service: "War Map Territory Builder" });
});

// Strategic balance advice & Secret Mission Deck Generator
app.post("/api/ai/strategy-advisor", async (req, res) => {
  try {
    const { territoryCount, continentDistribution, gameStyle, territoryList } = req.body;
    const ai = getGenAI();

    const prompt = `Você é um mestre designer de jogos de tabuleiro estratégicos (como War, Risk e Twilight Imperium).
Analise a seguinte configuração de mapa e territórios para o novo jogo de tabuleiro do usuário:
- Número de territórios ativos/agrupados: ${territoryCount}
- Estilo de jogo desejado: ${gameStyle || "Clássico War / Conquista Global"}
- Resumo de continentes e territórios: ${JSON.stringify(continentDistribution || {})}
- Amostra de territórios formados: ${JSON.stringify((territoryList || []).slice(0, 15))}

Por favor, forneça uma análise estruturada em JSON com:
1. "balanceScore" (número de 0 a 100 avaliando o equilíbrio estratégico para 3 a 6 jogadores)
2. "feedbackSummary" (visão geral em português sobre os gargalos e fluidez do mapa)
3. "recommendedContinentBonuses" (objeto com tropas extras recomendadas por continente para ficar justo)
4. "customMissions" (array com 4 cartas de objetivos secretos temáticos bem balanceados para esse mapa, cada um com "title", "description", "difficulty" [Fácil/Médio/Difícil])
5. "chokepointsInsight" (dicas sobre 2-3 regiões que se tornaram pontos de estrangulamento vitais)`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const jsonText = response.text || "{}";
    const data = JSON.parse(jsonText);
    res.json({ success: true, analysis: data });
  } catch (error: any) {
    console.error("Error in strategy advisor:", error);
    res.status(500).json({
      success: false,
      error: error.message || "Falha ao gerar análise estratégica",
    });
  }
});

// Board game card illustration generator with aspect ratio
app.post("/api/ai/generate-card-art", async (req, res) => {
  try {
    const { prompt, aspectRatio = "1:1", style = "vintage tactical boardgame illustration" } = req.body;
    const ai = getGenAI();

    const fullPrompt = `${prompt}, ${style}, high quality boardgame card artwork, rich colors, crisp line art, no text glitches, cinematic tabletop aesthetic.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-lite-image",
      contents: {
        parts: [{ text: fullPrompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
        },
      },
    });

    let imageUrl: string | null = null;
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          const mimeType = part.inlineData.mimeType || "image/png";
          imageUrl = `data:${mimeType};base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image generated by Gemini");
    }

    res.json({ success: true, imageUrl });
  } catch (error: any) {
    console.error("Error generating card art:", error);
    res.status(500).json({
      success: false,
      error: error.message || "Erro na geração de arte",
    });
  }
});

// Vite Middleware for development & static serving for production
async function start() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true, host: "0.0.0.0", port: 3000 },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Board Game Territory Builder Server running at http://localhost:${PORT}`);
  });
}

start();
